version: '3.3'

services:

  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    restart: always
    ports:
      - '8085:3000'
    volumes:
      - './storage/grafana/grafana.ini:/etc/grafana/grafana.ini'
      - './storage/grafana/data:/var/lib/grafana'
      - './storage/grafana/logs:/var/log/grafana'
      - './storage/grafana/provisioning:/etc/grafana/provisioning/'
      - './storage/grafana/dashboards:/tmp/dashboards/'

  influxdb:
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=f1
      - DOCKER_INFLUXDB_INIT_BUCKET=data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ruMprXfRhjX7f#6+=_9kCqw*XdN9?5Hw8dw^Q745Gq=-QKuY69XP!UnEry$W$v&Yd+T#w$QAt2v
    volumes:
      - './storage/influxdb:/var/lib/influxdb2'
